import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { Toaster } from "@/components/ui/toaster"
const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Chatify',
  description: 'Generated by Royal Software',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={font.style}>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
